export const LIST_EMPLOYEES = [
  {
    id: 1,
    firstName: 'Leanne ',
    lastName: 'Graham',
    login: 'Sincere123Graham',
    phone: '1-770-736-8031',
    workPhone: '44-770-736-8031',
    workEmail: 'Kulas@gmail.com',
    email: 'Sincere@april.biz',
    workLocation: 'Gwenborough',
    company: 'Kulas Light',
    role: 'designer',
    hourlyRate: '20/h',
    available: false
  },
  {
    id: 2,
    firstName: 'Ervin ',
    lastName: 'Howell',
    login: 'Shanna123Ervin',
    phone: '1-010-692-6593',
    workPhone: '44-90566-777',
    workEmail: 'Shanna@melissa.tv',
    email: 'Shanna@april.biz',
    workLocation: 'Wisokyburgh',
    company: 'Deckow-Crist',
    role: 'Proactive didactic contingency',
    hourlyRate: '20/h',
    available: false
  },
  {
    id: 3,
    firstName: 'Clementine ',
    lastName: 'Bauch',
    login: 'Samantha123Ervin',
    phone: '1-463-123-4447',
    workPhone: '1-244-90566-777',
    workEmail: 'ramiro.info',
    email: 'Nathan@yesenia.net',
    workLocation: 'McKenziehaven',
    company: 'Romaguera-Jacobson',
    role: 'Face to face bifurcated interface',
    hourlyRate: '10/h',
    available: false
  },
  {
    id: 4,
    firstName: 'Patricia ',
    lastName: 'Lebsack',
    login: 'SaKarianne90',
    phone: '1-493-170-9623',
    workPhone: '1-493-170-9623',
    workEmail: 'kale.biz',
    email: 'Julianne.OConner@kory.org',
    workLocation: 'South Elvis',
    company: 'Robel-Corkery',
    role: 'Multi-tiered zero tolerance productivity',
    hourlyRate: '19/h',
    available: false
  },
  {
    id: 5,
    firstName: 'Chelsey ',
    lastName: 'Dietrich',
    login: 'Kamrennne90',
    phone: '1-493-170-9623',
    workPhone: '1-(254)954-1289',
    workEmail: 'demarco@info',
    email: 'Lucio_Hettinger@annie.ca',
    workLocation: 'Roscoeview',
    company: 'Keebler LLC',
    role: 'User-centric fault-tolerant solution',
    hourlyRate: '15/h',
    available: false
  },
  {
    id: 6,
    firstName: 'Dennis ',
    lastName: 'Schulist',
    login: 'Leopoldo_Corkery',
    phone: '1-477-935-8471',
    workPhone: '1-(254)954-8471',
    workEmail: 'ola@info',
    email: 'Karley_Dach@jasper.info',
    workLocation: 'South Christy',
    company: 'Considine-Lockman',
    role: 'Synchronised bottom-line interface',
    hourlyRate: '20/h',
    available: false
  },
  {
    id: 7,
    firstName: 'Kurtis ',
    lastName: 'Weissnat',
    login: 'Elwyn.Skiles',
    phone: '1-411-912-3471',
    workPhone: '1-(254)954-8471',
    workEmail: 'elvis@info',
    email: 'Telly.Hoeger@billy.biz',
    workLocation: 'Howemouth',
    company: 'Johns Group',
    role: 'Configurable multimedia task-force',
    hourlyRate: '17/h',
    available: false
  },
  {
    id: 8,
    firstName: 'KuNicholas',
    lastName: 'Runolfsdottir V',
    login: 'Maxime_Nienow',
    phone: '1-123-912-3471',
    workPhone: '1-(122)954-8471',
    workEmail: 'jacynthe@info',
    email: 'Sherwood@rosamond.me',
    workLocation: 'Aliyaview',
    company: 'Abernathy Group',
    role: 'Implemented secondary concept',
    hourlyRate: '11/h',
    available: false
  },
  {
    id: 9,
    firstName: 'Glenna',
    lastName: 'Reichert',
    login: 'Delphine',
    phone: '1-777-912-1237',
    workPhone: '1-(775)976-6794',
    workEmail: 'conrad@info',
    email: 'Chaim_McDermott@dana.io',
    workLocation: 'Bartholomebury',
    company: 'Yost and Sons',
    role: 'Switchable contextually-based project',
    hourlyRate: '12/h',
    available: false
  },
  {
    id: 10,
    firstName: 'Clementina',
    lastName: 'DuBuque',
    login: 'Moriah',
    phone: '1-987-912-1237',
    workPhone: '1-024-648-3804',
    workEmail: 'ambrose@info',
    email: 'Rey.Padberg@karina.biz',
    workLocation: 'Lebsackbury',
    company: 'Hoeger LLC',
    role: 'Centralized empowering task-force',
    hourlyRate: '13/h',
    available: false
  }
];
